### ISSUE TITLE
Formalize schema

### ISSUE THREAD

**Issue by bollwyvl** [deathbeds/lintotype#3]
Concrete tasks:
- [ ] pick a data model
  - [ ] stay with CodeMirror
  - [ ] language server protocol
- [ ] pick a canonical form
  - [ ] traitlets
  - [ ] json schema
At present the request format is something like this:
```yaml
request_id: 123
cell_id: abc-123
code:
  text/x-ipython:
    - cell_id: abc-123
      code: x = 1\nx + "1"
metadata:
  text/x-ipython:
    mypy:
      args: --some-arg
```

The response format is something like:
```yaml
request_id: 123
annotations:
  text/x-ipython:
    - message: doh
      severity: error
      from: 
        line: 1
        char: 1
      to:
        line: 1
        char: 1
```

This is extremely close to the Language Server Protocol [Diagnostic](https://microsoft.github.io/language-server-protocol/specification#diagnostic):

```ts
interface Diagnostic {
	/**
	 * The range at which the message applies.
	 */
	range: Range;

	/**
	 * The diagnostic's severity. Can be omitted. If omitted it is up to the
	 * client to interpret diagnostics as error, warning, info or hint.
	 */
	severity?: number;

	/**
	 * The diagnostic's code, which might appear in the user interface.
	 */
	code?: number | string;

	/**
	 * A human-readable string describing the source of this
	 * diagnostic, e.g. 'typescript' or 'super lint'.
	 */
	source?: string;

	/**
	 * The diagnostic's message.
	 */
	message: string;

	/**
	 * An array of related diagnostic information, e.g. when symbol-names within
	 * a scope collide all definitions can be marked via this property.
	 */
	relatedInformation?: DiagnosticRelatedInformation[];
}
```

Given how much utility this has, we should go ahead and probably adopt it.

Options:
- TypedDict
- traitlets

Going "LSP-native" will require writing a _client-side_ transformer for 
CodeMirror, but this is manageable.
